"""Settings for sourukorekuta."""
# Database Settings
db_host = ''
db_name = ''
db_user = ''
db_password = ''
db_port = ''
# Bot Settings
bottoken = ''
# Userbot Settings
ub_api_id = ''
ub_api_hash = ''
ub_phone = ''
